$htmlheader(whichCss="posts")$
<body>
  <div id="page">
    <div id="topbar">
    $header()$
    $navigation()$
    </div>

    <div id="content">
      <div id="about">
        <h2>about me (list format)</h2>

        <ul>
          <li>I'm a 29-year old computer programmer and musician
            living in Toronto, Canada with my wife Amy Emel.</li>
          <li>I did an MSc. in Computer
            Science <a href="http://flint.cs.yale.edu/">here</a>.</li>
          <li>I work at <a href="http://www.polarmobile.com/">Polar
            Mobile</a>, a provider of content-delivery applications
            for smartphones.</li>
          <li>I enjoy playing basketball.</li>
          <li>I used to be in <a href="http://ninjahighschool.info/">a
            positive hardcore rap group</a>.</li>
        </ul>
      </div>
    </div>
  </div>
$footer()$
  </body>
</html>
