$htmlheader()$
<body>
  <div id="page">
    <div id="topbar">
    $header()$
    $navigation()$
    </div>

    <div id="content">
      <div id="about">
        <h2>contact me</h2>
        <p>You can email me at:
          <script type="text/javascript">
            <!--
                h='&#x67;&#114;&#x65;&#x67;&#x6f;&#114;&#x79;&#x63;&#x6f;&#108;&#108;&#x69;&#110;&#x73;&#46;&#110;&#x65;&#116;';a='&#64;';n='&#x67;&#114;&#x65;&#x67;';e=n+a+h;
                document.write('<a h'+'ref'+'="ma'+'ilto'+':'+e+'">'+'<code>'+e+'</code>'+'<\/'+'a'+'>');
                // -->
          </script><noscript>&#x67;&#114;&#x65;&#x67;&#32;&#x61;&#116;&#32;&#x67;&#114;&#x65;&#x67;&#x6f;&#114;&#x79;&#x63;&#x6f;&#108;&#108;&#x69;&#110;&#x73;&#32;&#100;&#x6f;&#116;&#32;&#110;&#x65;&#116;</noscript>, or connect with me on <a href="http://www.linkedin.com/in/gregorydavidcollins">LinkedIn</a></p>
      </div>
    </div>
  </div>
$footer()$
  </body>
</html>
