        <div class="post-comments">
          <h3>Comments</h3>
          <div id="disqus_thread"></div>
          <script type="text/javascript"
                  src="http://disqus.com/forums/gregorycollins/embed.js"></script>
          <noscript><a href="http://gregorycollins.disqus.com/?url=ref">View
              the discussion
              thread.</a></noscript><a href="http://disqus.com"
                                       class="dsq-brlink">blog comments powered
            by <span class="logo-disqus">Disqus</span></a>
        </div>
